### ISSUE TITLE
error with installing requirements

### ISSUE THREAD

**Issue by dasiff** [rougier/numpy-100#219]
I tried to install the requirements in a command-prompt and received the following error:

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\dasif\AppData\Local\Temp\pip-install-kyujez_f\pandas_c7008c6059444298becd7cdbf2cd9dc3\setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dasif\AppData\Local\Temp\pip-install-kyujez_f\pandas_c7008c6059444298becd7cdbf2cd9dc3\setup.py", line 812, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dasif\AppData\Local\Temp\pip-install-kyujez_f\pandas_c7008c6059444298becd7cdbf2cd9dc3\versioneer.py", line 1440, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\dasif\AppData\Local\Temp\pip-install-kyujez_f\pandas_c7008c6059444298becd7cdbf2cd9dc3\versioneer.py", line 1369, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dasif\AppData\Local\Temp\pip-install-kyujez_f\pandas_c7008c6059444298becd7cdbf2cd9dc3\versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jeqcho** [comment]
I tried to run `initialise.py` in the jupyter notebook and got some import errors, so I tried to `pip install -r requirements.txt` but I got the error above. I decided to ignore the `requirements.txt` and manually import the few modules required until `initialise.py` works. Then I can run `hint(n)` and `answer(n)` as desired.
